[versions]
junit = { strictly = '5.11.3' }
assertj = { strictly = '3.26.3' }
hamcrest = { strictly = '3.0' }



[libraries]


junit-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'junit' }
junit-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'junit' }
junit-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version = 'junit' }

assertj = { group = 'org.assertj', name = 'assertj-core', version.ref = 'assertj' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }


[bundles]
testing = ['junit-api', 'junit-engine', 'junit-params',  'assertj', 'hamcrest']
